### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by limelect** [AngusJohnson/Image32#1]
D10.2.3
Img32.Clipper>Img32.Clipper2
Img32.Ctrl.pas where is TStorageManager???
ON G:\Delphi Projects\AngusJohnson\Image32-main\Examples\SVG2\main.pas
 Svg.width := 250;
      Svg.height := 300;  does not exsist

fontInfo.family := ttfSansSerif;
          fontInfo.size := 12; not declare
and may be more

**Comment by AngusJohnson** [comment]
Thanks. Hopefully fixed now.

**Comment by limelect** [comment]
On the librery package
 change to Img32.Clipper2
had to remove and add Clipper.Core

NOT FIXED
ON G:\Delphi Projects\AngusJohnson\Image32-main\Examples\SVG2\main.pas
Svg.width := 250;
Svg.height := 300; does not exsist

fontInfo.family := ttfSansSerif;
fontInfo.size := 12; not declare

**Comment by limelect** [comment]
[ProjectGroup1.zip](https://github.com/AngusJohnson/Image32/files/8802624/ProjectGroup1.zip)
Use that for demo group
